### ISSUE TITLE
Saturation greater than 1 not reacting in tga

### ISSUE THREAD

**Issue by StanHustler** [yegor-pelykh/image-in-browser#3] opened 2023-11-20 17:31 UTC
> [Wiki](https://github.com/yegor-pelykh/image-in-browser/wiki/Image-Filter-Functions#adjustcolor) saturation  >1:  the image becomes more saturated.

The part less than 1 works fine, I made a demo to reproduce it.

![Kapture 2023-11-21 at 01 23 57](https://github.com/yegor-pelykh/image-in-browser/assets/62613346/a4b6397c-60df-4962-a80d-22a9411b33d0)

**Comment by yegor-pelykh** [comment] 2024-02-06 15:16
Sorry @StanHustler, I didn't understand what the problem is. Could you please describe in more detail what you are trying to achieve and what is not working correctly?

**Comment by yegor-pelykh** [comment] 2024-04-12 21:19
Hi @StanHustler,
Now I figured out the problem.
This has been fixed by eba6a92 in a recent release v2.4.0.

**Closed by yegor-pelykh** 2024-04-12 21:19 UTC
